# starship.toml

#-- Prompt --------------------------------------------------------------------

format = """ï¼  \
    $directory\
    $c\
    $golang\
    $julia\
    $lua\
    $python\
    $rust\
    $git_branch\
    $git_status
[ó°˜³  ](blue bold)"""


#-- Git -----------------------------------------------------------------------

[git_branch]
symbol = 'ï„¦ '
truncation_length = 20
truncation_symbol = ''
style = "fg:#20ff20"

[git_status]
disabled = false
ahead = "ó°™ ${count} "
behind = "ó°’ ${count} "
conflicted = "ï€¤ ${count} "
deleted = "ï’ ${count} "
diverged = "ó°µ‰ ${ahead_count},${behind_count} "
modified = "ï„ ${count} "
renamed = "ï„­ ${count} "
staged = "ï‡™ ${count} "
stashed = "ï€œ ${count} "
up_to_date = "monke"
untracked = "ó±…˜ ${count} "
style = "fg:#55ff55"
format = "$style$stashed$ahead$behind$diverged$conflicted$deleted$renamed$modified$staged$untracked"


#-- Languages -----------------------------------------------------------------

[c]
disabled = false
symbol = "î˜ "
style = "fg:#007ACC"

[golang]
disabled = false
symbol = "ğŸ¹ "
style = "fg:#00ADD8 "

[julia]
disabled = false
symbol = "î˜¤ "
style = "fg:#9558B2"

[lua]
disabled = false
symbol = "î˜  "
style = "fg:#000080"

[python]
disabled = false
pyenv_version_name = true
python_binary = 'python3'
style = "fg:#3776AB"
symbol = "îœ¼ "

[rust]
disabled = false
symbol = "ğŸ¦€ "
style = "fg:#FF2525"


#-- Shell ---------------------------------------------------------------------

[cmd_duration]
min_time = 10_000
format = "took [$duration]($style)"

[directory]
truncation_length = 10

