
# alacritty.toml

# ---------------------------------------------------------
# -- Basic Window -----------------------------------------

[window]
title = "terminal"
opacity = 0.7
blur = true
dimensions = { columns = 120, lines = 29 }
position = { x = 600, y = 700 }
padding = { x = 5, y = 5 }
option_as_alt = "Both"
resize_increments = true

[cursor]
style = "Block"
unfocused_hollow = true

[colors.primary]
foreground = "0xe6e6e6"
background = "0x000000"

[colors.line_indicator]
background = "None"
foreground = "None"

[[keyboard.bindings]]
key = "F"
mods = "Alt"
action = "ToggleSimpleFullscreen"


# ---------------------------------------------------------
# -- Fonts ------------------------------------------------

[font]
size = 14

[font.bold]
family = "JetBrainsMono NF"
style = "Bold"

[font.italic]
family = "JetBrainsMono NF"
style = "Italic"

[font.normal]
family = "JetBrainsMono NF"
style = "Regular"

